name: hpnlg_py38
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.10.8=ha878542_0
  - certifi=2021.10.8=py38h578d9bd_0
  - cudatoolkit=10.2.89=hfd86e86_1
  - debugpy=1.4.1=py38h709712a_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.4.2=py38he5a9106_0
  - ipython=7.28.0=py38he5a9106_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py38h578d9bd_2
  - jpeg=9b=h024ee3a_2
  - jupyter_client=7.0.6=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py38h578d9bd_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - numpy=1.21.2=py38h20f2e39_0
  - numpy-base=1.21.2=py38h79a1101_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1l=h7f8727e_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h5aabda8_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - pytorch=1.8.0=py3.8_cuda10.2_cudnn7.6.5_0
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.8.0=py38
  - torchvision=0.9.0=py38_cu102
  - tornado=6.1=py38h497a2fe_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==0.15.0
    - aiohttp==3.7.4.post0
    - alabaster==0.7.12
    - async-timeout==3.0.1
    - attrs==21.2.0
    - babel==2.9.1
    - beautifulsoup4==4.6.0
    - bengali-stemmer==0.0.1
    - chardet==4.0.0
    - charset-normalizer==2.0.7
    - click==8.0.3
    - colorama==0.4.4
    - datasets==1.14.0
    - dawg-python==0.7.2
    - dill==0.3.4
    - docopt==0.6.2
    - docutils==0.17.1
    - filelock==3.3.1
    - fsspec==2021.10.1
    - fugashi==1.1.1
    - higher==0.2.1
    - huggingface-hub==0.0.19
    - idna==3.3
    - imagesize==1.2.0
    - indic-nlp-library==0.81
    - install==1.3.4
    - ipadic==1.0.0
    - jieba==0.42.1
    - jinja2==3.0.2
    - joblib==1.1.0
    - jpype1==1.3.0
    - konlpy==0.5.2
    - lxml==4.6.3
    - markupsafe==2.0.1
    - mecab-python3==1.0.4
    - morfessor==2.0.6
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - nlpo3==1.1.3
    - nltk==3.6.5
    - oauthlib==3.1.1
    - packaging==21.0
    - pandas==1.3.4
    - pip==21.3.1
    - plac==1.3.3
    - portalocker==2.3.2
    - pyarrow==5.0.0
    - pymorphy2==0.9.1
    - pymorphy2-dicts-ru==2.4.417127.4579844
    - pyonmttok==1.29.0
    - pyparsing==2.4.7
    - pysocks==1.7.1
    - pythainlp==2.3.2
    - python-crfsuite==0.9.7
    - pytz==2021.3
    - pyvi==0.1.1
    - pyyaml==6.0
    - regex==2021.10.8
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - sacrebleu==2.0.0
    - sacremoses==0.0.46
    - scikit-learn==1.0
    - scipy==1.7.1
    - sentencepiece==0.1.96
    - sklearn-crfsuite==0.3.6
    - snowballstemmer==2.1.0
    - sphinx==4.2.0
    - sphinx-argparse==0.3.1
    - sphinx-rtd-theme==1.0.0
    - sphinxcontrib-applehelp==1.0.2
    - sphinxcontrib-devhelp==1.0.2
    - sphinxcontrib-htmlhelp==2.0.0
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.3
    - sphinxcontrib-serializinghtml==1.1.5
    - tabulate==0.8.9
    - threadpoolctl==3.0.0
    - tinydb==4.5.2
    - tokenizers==0.10.3
    - tqdm==4.62.3
    - transformers==4.11.3
    - trtokenizer==0.0.3
    - turkishstemmer==1.3
    - tweepy==3.10.0
    - unidic==1.1.0
    - unidic-lite==1.0.8
    - urllib3==1.26.7
    - wasabi==0.8.2
    - xxhash==2.0.2
    - yarl==1.7.0
prefix: /raid/kaushal/anaconda3/envs/hpnlg_py38
